# 単回帰分析

傾き$a$の計算式
\begin{align}
a = \frac{\sum_{n=1}^{N}x_{n}y_{n}}{\sum_{n=1}^{N}{x_{n}}^2}
\end{align}

サンプルデータ

|x|y|
|--|--|
| 1| 2|
|2|3.9|
|3|6.1|

In [1]:
import numpy as np

In [3]:
x = np.array([1,2,3])

In [4]:
x

array([1, 2, 3])

In [10]:
y = np.array([2,3.9,6.1])

In [11]:
y

array([2. , 3.9, 6.1])

In [12]:
x.mean()

2.0

In [13]:
y.mean()

4.0

In [14]:
xc = x - x.mean()

In [15]:
xc

array([-1.,  0.,  1.])

In [16]:
yc = y - y.mean()

In [17]:
yc

array([-2. , -0.1,  2.1])

In [20]:
xx = xc * xc

In [21]:
xx

array([1., 0., 1.])

In [23]:
xy = xc * yc

In [24]:
xy

array([ 2. , -0. ,  2.1])

In [25]:
xx.sum()

2.0

In [26]:
xy.sum()

4.1

In [27]:
a = xy.sum()/xx.sum()

In [28]:
a

2.05

# Pandas : データベースの操作

In [29]:
import pandas as pd